name: build

on: [push, pull_request]

jobs:
  list-compilers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
    - run: dpkg --list | grep compiler
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-7, clang++-6.0]
    env:
      CXX: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - run: $CXX --version
    - run: make
    - run: ./a
